[package]
name = "sys"
version = "0.1.0"
edition = "2021"

[dependencies]
error = { path = "../error" }
sysinfo = "0.37.2"
tokio = { version = "1.47.1", features = ["full"] }

[lib]
name = "sys"
path = "src/lib.rs"

[features]
default = []
